M48
; DRILL file {KiCad 7.0.10} date Thu Jul  4 23:27:21 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-04T23:27:21-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X1.1Y-1.1
X1.1Y-5.8
X6.4Y-1.1
X6.4Y-5.9
T2
X4.8Y-3.5075
X5.3Y-3.5075
M30
